apiVersion: v2
name: kdt-web
description: Interface web de kdt, adossée à kdt-identity
type: application
version: 2.0.0-beta.4
appVersion: "2.0.0-beta.4"
home: https://github.com/agardenat/kdt
sources:
  - https://github.com/agardenat/kdt
keywords: [kubernetes, diagnostic, flux, web]
