use crate::ai::AiLanguage;

#[allow(dead_code)]
pub struct Strings {
    pub mode_live: &'static str,
    pub mode_selection: &'static str,
    pub mode_ns: &'static str,
    pub mode_ai: &'static str,
    pub mode_detail: &'static str,
    pub mode_nodes: &'static str,
    pub mode_node_detail: &'static str,
    pub mode_node_usage: &'static str,
    pub mode_diagnostic: &'static str,
    pub mode_extract: &'static str,

    pub k_quit: &'static str,
    pub k_select: &'static str,
    pub k_namespace: &'static str,
    pub k_nodes: &'static str,
    pub k_diag: &'static str,
    pub k_extract: &'static str,
    pub k_back: &'static str,
    pub k_close: &'static str,
    pub k_zoom: &'static str,
    pub k_nav: &'static str,
    pub k_view: &'static str,
    pub k_scroll: &'static str,
    pub k_h_scroll: &'static str,
    pub k_page: &'static str,
    pub k_top_bot: &'static str,
    pub k_split: &'static str,
    pub k_ai: &'static str,
    pub k_refresh: &'static str,
    pub k_sort: &'static str,
    pub k_relaunch: &'static str,
    pub k_pdf: &'static str,
    pub k_send_to_ai: &'static str,
    pub k_confirm: &'static str,
    pub k_cancel: &'static str,
    pub k_lang: &'static str,
    pub k_provider: &'static str,
    pub k_node_usage: &'static str,
    pub k_filter_all: &'static str,
    pub k_filter_warn: &'static str,
    pub k_filter_err: &'static str,
    pub k_freeze: &'static str,
    pub k_unfreeze: &'static str,

    pub title_node_usage: &'static str,
    pub title_diagnostic: &'static str,
    pub title_namespace: &'static str,
    pub title_ai_analysis: &'static str,
    pub title_extraction: &'static str,
    pub title_extraction_running: &'static str,
    pub title_extraction_finished: &'static str,
    pub title_extraction_error: &'static str,

    pub lbl_loading: &'static str,
    pub lbl_preparation: &'static str,
    pub lbl_ready: &'static str,
    pub lbl_running: &'static str,
    pub lbl_finished: &'static str,
    pub lbl_error: &'static str,
    pub lbl_step: &'static str,
    pub lbl_steps: &'static str,
    pub lbl_duration: &'static str,
    pub lbl_metrics_ok: &'static str,
    pub lbl_metrics_unavailable: &'static str,
    pub lbl_no_response: &'static str,
    pub lbl_model: &'static str,
    pub lbl_pdf_generating: &'static str,
    pub lbl_pdf_exported: &'static str,
    pub lbl_pdf_error: &'static str,
    pub lbl_pdf_pdf_label: &'static str,
    pub lbl_user_containers: &'static str,
    pub lbl_system_containers: &'static str,
    pub lbl_dont_close: &'static str,
    pub lbl_press_esc_close: &'static str,
    pub lbl_extraction_failed: &'static str,
    pub lbl_extraction_done: &'static str,
    pub lbl_node: &'static str,
    pub lbl_namespace: &'static str,
    pub lbl_context: &'static str,
    pub lbl_generated: &'static str,
    pub lbl_all_namespaces: &'static str,
    pub lbl_select_namespace: &'static str,
    pub lbl_export_empty_diag: &'static str,
    pub lbl_export_empty_usage: &'static str,
    pub lbl_filter_label_all: &'static str,
    pub lbl_filter_label_warn: &'static str,
    pub lbl_filter_label_err: &'static str,
    pub lbl_split: &'static str,
    pub lbl_total_label: &'static str,
    pub lbl_summary: &'static str,
    pub lbl_containers_to_watch: &'static str,
    pub lbl_no_issue: &'static str,
    pub lbl_recap: &'static str,
    pub lbl_node_diagnostic: &'static str,

    pub ai_send_to_ai_legend: &'static str,
    pub hint_select_copy: &'static str,

    pub progress_init: &'static str,
    pub progress_list_nodes: &'static str,
    pub progress_diag_collect: &'static str,
    pub progress_diag_ai: &'static str,
    pub progress_node_usage_fmt: &'static str,
    pub progress_node_ai_fmt: &'static str,
    pub progress_pdf: &'static str,
    pub progress_pdf_done: &'static str,
}

pub const FR: Strings = Strings {
    mode_live: "DIRECT",
    mode_selection: "SÉLECTION",
    mode_ns: "NS",
    mode_ai: "IA",
    mode_detail: "DÉTAIL",
    mode_nodes: "NOEUDS",
    mode_node_detail: "DÉTAIL-NOEUD",
    mode_node_usage: "USAGE-NOEUD",
    mode_diagnostic: "DIAGNOSTIC",
    mode_extract: "EXTRACTION",

    k_quit: "quitter",
    k_select: "sélection",
    k_namespace: "namespace",
    k_nodes: "noeuds",
    k_diag: "diag",
    k_extract: "extraction→PDF",
    k_back: "retour",
    k_close: "fermer",
    k_zoom: "zoom détail",
    k_nav: "nav",
    k_view: "vue",
    k_scroll: "défil.",
    k_h_scroll: "défil. h.",
    k_page: "page",
    k_top_bot: "haut/bas",
    k_split: "split",
    k_ai: "IA",
    k_refresh: "rafraîchir",
    k_sort: "tri",
    k_relaunch: "relancer",
    k_pdf: "PDF",
    k_send_to_ai: "envoyer à l'IA",
    k_confirm: "valider",
    k_cancel: "annuler",
    k_lang: "lang",
    k_provider: "IA",
    k_node_usage: "usage",
    k_filter_all: "tous",
    k_filter_warn: "avert.",
    k_filter_err: "err.",
    k_freeze: "geler",
    k_unfreeze: "dégeler",

    title_node_usage: "Usage du noeud",
    title_diagnostic: "Diagnostic cluster",
    title_namespace: "Namespace",
    title_ai_analysis: "Analyse IA",
    title_extraction: "Extraction",
    title_extraction_running: "Extraction en cours — ne pas fermer",
    title_extraction_finished: "Extraction — terminée",
    title_extraction_error: "Extraction — erreur",

    lbl_loading: "Chargement...",
    lbl_preparation: "Préparation...",
    lbl_ready: "prêt",
    lbl_running: "en cours…",
    lbl_finished: "terminé",
    lbl_error: "erreur",
    lbl_step: "Étape",
    lbl_steps: "étapes",
    lbl_duration: "durée",
    lbl_metrics_ok: "metrics-server : disponible",
    lbl_metrics_unavailable: "metrics-server : indisponible (use=—)",
    lbl_no_response: "(pas de réponse IA)",
    lbl_model: "Modèle",
    lbl_pdf_generating: "génération PDF (typst)...",
    lbl_pdf_exported: "exporté",
    lbl_pdf_error: "erreur export",
    lbl_pdf_pdf_label: "PDF",
    lbl_user_containers: "User containers",
    lbl_system_containers: "System containers",
    lbl_dont_close: "ne pas fermer",
    lbl_press_esc_close: "appuyer sur Esc pour fermer",
    lbl_extraction_failed: "Échec de l'extraction",
    lbl_extraction_done: "Extraction terminée",
    lbl_node: "Noeud",
    lbl_namespace: "Namespace",
    lbl_context: "Contexte",
    lbl_generated: "Généré",
    lbl_all_namespaces: "(tous les namespaces)",
    lbl_select_namespace: "Namespace · ↑↓ nav · Entrée valider · Esc annuler",
    lbl_export_empty_diag: "rien à exporter (diagnostic vide)",
    lbl_export_empty_usage: "rien à exporter (usage vide)",
    lbl_filter_label_all: "TOUS",
    lbl_filter_label_warn: "AVERT",
    lbl_filter_label_err: "ERR",
    lbl_split: "split",
    lbl_total_label: "total",
    lbl_summary: "Bilan",
    lbl_containers_to_watch: "Conteneurs à surveiller",
    lbl_no_issue: "Aucun conteneur avec un problème détecté.",
    lbl_recap: "Récap",
    lbl_node_diagnostic: "Diagnostic du noeud",

    ai_send_to_ai_legend: "envoie le rapport à l'IA",
    hint_select_copy: "Maj+glisser pour sélectionner / copier",

    progress_init: "Initialisation...",
    progress_list_nodes: "Liste des noeuds...",
    progress_diag_collect: "Diagnostic — collecte des indicateurs cluster...",
    progress_diag_ai: "Diagnostic — analyse IA...",
    progress_node_usage_fmt: "Noeud {i}/{n} — usage : {name}",
    progress_node_ai_fmt: "Noeud {i}/{n} — analyse IA : {name}",
    progress_pdf: "Génération du PDF...",
    progress_pdf_done: "PDF généré",
};

pub const EN: Strings = Strings {
    mode_live: "LIVE",
    mode_selection: "SELECT",
    mode_ns: "NS",
    mode_ai: "AI",
    mode_detail: "DETAIL",
    mode_nodes: "NODES",
    mode_node_detail: "NODE-DETAIL",
    mode_node_usage: "NODE-USAGE",
    mode_diagnostic: "DIAGNOSTIC",
    mode_extract: "EXTRACT",

    k_quit: "quit",
    k_select: "select",
    k_namespace: "namespace",
    k_nodes: "nodes",
    k_diag: "diag",
    k_extract: "extract→PDF",
    k_back: "back",
    k_close: "close",
    k_zoom: "zoom",
    k_nav: "nav",
    k_view: "view",
    k_scroll: "scroll",
    k_h_scroll: "h-scroll",
    k_page: "page",
    k_top_bot: "top/bot",
    k_split: "split",
    k_ai: "AI",
    k_refresh: "refresh",
    k_sort: "sort",
    k_relaunch: "rerun",
    k_pdf: "PDF",
    k_send_to_ai: "send to AI",
    k_confirm: "confirm",
    k_cancel: "cancel",
    k_lang: "lang",
    k_provider: "IA",
    k_node_usage: "usage",
    k_filter_all: "all",
    k_filter_warn: "warn",
    k_filter_err: "err",
    k_freeze: "freeze",
    k_unfreeze: "unfreeze",

    title_node_usage: "Node usage",
    title_diagnostic: "Cluster diagnostic",
    title_namespace: "Namespace",
    title_ai_analysis: "AI analysis",
    title_extraction: "Extraction",
    title_extraction_running: "Extraction running — do not close",
    title_extraction_finished: "Extraction — done",
    title_extraction_error: "Extraction — error",

    lbl_loading: "Loading...",
    lbl_preparation: "Preparing...",
    lbl_ready: "ready",
    lbl_running: "running…",
    lbl_finished: "done",
    lbl_error: "error",
    lbl_step: "Step",
    lbl_steps: "steps",
    lbl_duration: "duration",
    lbl_metrics_ok: "metrics-server: available",
    lbl_metrics_unavailable: "metrics-server: unavailable (use=—)",
    lbl_no_response: "(no AI response)",
    lbl_model: "Model",
    lbl_pdf_generating: "generating PDF (typst)...",
    lbl_pdf_exported: "exported",
    lbl_pdf_error: "export error",
    lbl_pdf_pdf_label: "PDF",
    lbl_user_containers: "User containers",
    lbl_system_containers: "System containers",
    lbl_dont_close: "do not close",
    lbl_press_esc_close: "press Esc to close",
    lbl_extraction_failed: "Extraction failed",
    lbl_extraction_done: "Extraction completed",
    lbl_node: "Node",
    lbl_namespace: "Namespace",
    lbl_context: "Context",
    lbl_generated: "Generated",
    lbl_all_namespaces: "(all namespaces)",
    lbl_select_namespace: "Namespace · ↑↓ nav · Enter confirm · Esc cancel",
    lbl_export_empty_diag: "nothing to export (empty diagnostic)",
    lbl_export_empty_usage: "nothing to export (empty usage)",
    lbl_filter_label_all: "ALL",
    lbl_filter_label_warn: "WARN",
    lbl_filter_label_err: "ERR",
    lbl_split: "split",
    lbl_total_label: "total",
    lbl_summary: "Summary",
    lbl_containers_to_watch: "Containers to watch",
    lbl_no_issue: "No container issue detected.",
    lbl_recap: "Recap",
    lbl_node_diagnostic: "Node diagnostic",

    ai_send_to_ai_legend: "send the report to AI",
    hint_select_copy: "Shift+drag to select / copy",

    progress_init: "Initialising...",
    progress_list_nodes: "Listing nodes...",
    progress_diag_collect: "Diagnostic — collecting cluster indicators...",
    progress_diag_ai: "Diagnostic — AI analysis...",
    progress_node_usage_fmt: "Node {i}/{n} — usage: {name}",
    progress_node_ai_fmt: "Node {i}/{n} — AI analysis: {name}",
    progress_pdf: "Generating PDF...",
    progress_pdf_done: "PDF generated",
};

pub fn t(lang: AiLanguage) -> &'static Strings {
    match lang {
        AiLanguage::Fr => &FR,
        AiLanguage::En => &EN,
    }
}
