//! Static FR/EN UI string tables, selected at runtime via [`t`].

use crate::ai::AiLanguage;

// `dead_code` is allowed because this is a translation table kept complete on purpose:
// several entries are reserved for UI strings not yet wired up and are intentionally unused.
#[allow(dead_code)]
pub struct Strings {
    pub mode_live: &'static str,
    pub mode_selection: &'static str,
    pub mode_ns: &'static str,
    pub mode_ai: &'static str,
    pub mode_detail: &'static str,
    pub mode_nodes: &'static str,
    pub mode_node_detail: &'static str,
    pub mode_node_usage: &'static str,
    pub mode_diagnostic: &'static str,
    pub mode_extract: &'static str,
    pub mode_command: &'static str,
    pub mode_search: &'static str,
    pub search_hint_table: &'static str,
    pub search_hint_text: &'static str,
    pub mode_flux: &'static str,
    pub mode_pods: &'static str,
    pub mode_rbac: &'static str,
    pub mode_vuln: &'static str,
    pub mode_secrets: &'static str,
    pub mode_certs: &'static str,
    pub k_origin_cert: &'static str,
    pub k_cert_actions: &'static str,
    pub k_goto_secret: &'static str,
    pub k_renew: &'static str,
    pub k_acme_retry: &'static str,
    pub mode_kyverno: &'static str,
    pub k_ky_by_resource: &'static str,
    pub k_ky_by_policy: &'static str,
    pub k_ky_filter: &'static str,
    pub mode_configmaps: &'static str,
    pub mode_services: &'static str,
    pub k_net_flat: &'static str,
    pub k_net_byclass: &'static str,

    pub k_quit: &'static str,
    pub k_select: &'static str,
    pub k_namespace: &'static str,
    pub k_nodes: &'static str,
    pub k_command: &'static str,
    pub k_search: &'static str,
    pub k_log_prev: &'static str,
    pub k_log_container: &'static str,
    pub k_log_follow: &'static str,
    pub k_flux: &'static str,
    pub k_diag: &'static str,
    pub k_extract: &'static str,
    pub k_back: &'static str,
    pub k_close: &'static str,
    pub k_zoom: &'static str,
    pub k_nav: &'static str,
    pub k_view: &'static str,
    pub k_scroll: &'static str,
    pub k_h_scroll: &'static str,
    pub k_page: &'static str,
    pub k_top_bot: &'static str,
    pub k_split: &'static str,
    pub k_ai: &'static str,
    pub k_refresh: &'static str,
    pub k_sort: &'static str,
    pub k_relaunch: &'static str,
    pub k_pdf: &'static str,
    pub k_send_to_ai: &'static str,
    pub k_confirm: &'static str,
    pub k_cancel: &'static str,
    pub k_lang: &'static str,
    pub k_provider: &'static str,
    pub k_node_usage: &'static str,
    pub k_filter_all: &'static str,
    pub k_filter_warn: &'static str,
    pub k_filter_err: &'static str,
    pub k_freeze: &'static str,
    pub k_unfreeze: &'static str,
    pub k_reconcile: &'static str,
    pub k_reconcile_src: &'static str,
    pub k_sync_root: &'static str,
    pub k_suspend: &'static str,
    pub k_tree: &'static str,
    pub k_inventory: &'static str,
    pub k_fold: &'static str,
    pub k_flux_logs: &'static str,
    pub k_pods: &'static str,
    pub k_origin: &'static str,
    pub k_scale_up: &'static str,
    pub k_scale_down: &'static str,
    pub k_scale_zero: &'static str,
    pub k_rescale: &'static str,
    pub k_force: &'static str,
    pub k_restart: &'static str,
    pub k_actions: &'static str,
    pub k_rbac_filter: &'static str,
    pub k_scale: &'static str,
    pub k_scale_set: &'static str,
    pub k_toggle_wl: &'static str,
    pub k_ns_here: &'static str,
    pub k_copy: &'static str,
    pub k_reveal_b64: &'static str,
    pub k_reveal_plain: &'static str,
    pub k_yaml: &'static str,
    pub k_yaml_toggle: &'static str,
    pub lbl_yaml_neat: &'static str,
    pub lbl_yaml_raw: &'static str,
    pub k_delete: &'static str,

    pub delete_title: &'static str,
    // Keys that answer "no" in the delete panel, spelled in the UI language.
    pub delete_cancel_keys: &'static str,
    pub delete_target: &'static str,
    pub delete_checking: &'static str,
    pub delete_no_object: &'static str,
    pub delete_no_finding: &'static str,
    pub delete_check_failed: &'static str,
    pub delete_arm_prompt: &'static str,
    pub delete_confirm_prompt: &'static str,
    pub delete_strict_hint: &'static str,
    pub delete_strict_prompt: &'static str,
    pub delete_strict_mismatch: &'static str,
    pub delete_running: &'static str,
    pub delete_ok: &'static str,
    pub delete_failed: &'static str,
    pub del_flux_ks: &'static str,
    pub del_flux_hr: &'static str,
    pub del_argo: &'static str,
    pub del_helm: &'static str,
    pub del_gitops_root: &'static str,
    pub del_namespace: &'static str,
    pub del_crd: &'static str,
    pub del_owned: &'static str,
    pub del_system_ns: &'static str,
    pub del_node: &'static str,
    pub del_persistent: &'static str,
    pub del_finalizers: &'static str,

    pub k_edit: &'static str,
    pub edit_title: &'static str,
    pub edit_target: &'static str,
    pub edit_checking: &'static str,
    pub edit_no_object: &'static str,
    pub edit_load_failed: &'static str,
    pub edit_open_prompt: &'static str,
    pub edit_editor_running: &'static str,
    pub edit_editor_failed: &'static str,
    pub edit_no_change: &'static str,
    pub edit_parse_error: &'static str,
    pub edit_reedit_prompt: &'static str,
    pub edit_changes: &'static str,
    pub edit_more_changes: &'static str,
    pub edit_apply_prompt: &'static str,
    pub edit_applying: &'static str,
    pub edit_ok: &'static str,
    pub edit_failed: &'static str,
    pub edit_noop: &'static str,
    pub edit_server_owned: &'static str,
    pub edit_immutable: &'static str,
    pub edit_identity: &'static str,
    pub edit_header_object: &'static str,
    pub edit_header_hint: &'static str,
    pub ed_flux_ks: &'static str,
    pub ed_flux_hr: &'static str,
    pub ed_argo: &'static str,
    pub ed_helm: &'static str,
    pub ed_owned: &'static str,
    pub ed_terminating: &'static str,
    pub ed_completed: &'static str,
    pub ed_forbidden: &'static str,
    pub ed_immutable_obj: &'static str,
    pub ed_running_pod: &'static str,
    pub ed_partial_spec: &'static str,

    pub k_touch: &'static str,
    /// Same key, said out loud where a row is an Event and not the object it patches.
    pub k_touch_object: &'static str,
    pub touch_no_object: &'static str,
    pub touch_running: &'static str,
    pub touch_ok: &'static str,
    pub touch_failed: &'static str,

    pub menu_pods_title: &'static str,
    pub menu_flux_title: &'static str,
    pub menu_certs_title: &'static str,
    pub desc_renew: &'static str,
    pub desc_acme_retry: &'static str,
    pub menu_scale_title: &'static str,
    pub menu_hint: &'static str,
    pub menu_confirm_prompt: &'static str,
    pub menu_input_prompt: &'static str,
    pub desc_rescale: &'static str,
    pub desc_recycle: &'static str,
    pub desc_restart: &'static str,
    pub desc_reconcile: &'static str,
    pub desc_reconcile_src: &'static str,
    pub desc_sync_root: &'static str,
    pub desc_scale_up: &'static str,
    pub desc_scale_down: &'static str,
    pub desc_scale_zero: &'static str,
    pub desc_scale_set: &'static str,

    pub title_node_usage: &'static str,
    pub title_diagnostic: &'static str,
    pub title_namespace: &'static str,
    pub title_ai_analysis: &'static str,
    pub title_extraction: &'static str,
    pub title_extraction_running: &'static str,
    pub title_extraction_finished: &'static str,
    pub title_extraction_error: &'static str,

    pub lbl_loading: &'static str,
    pub lbl_preparation: &'static str,
    pub lbl_ready: &'static str,
    pub lbl_running: &'static str,
    pub lbl_finished: &'static str,
    pub lbl_error: &'static str,
    pub lbl_step: &'static str,
    pub lbl_steps: &'static str,
    pub lbl_duration: &'static str,
    pub lbl_metrics_ok: &'static str,
    pub lbl_metrics_unavailable: &'static str,
    pub lbl_no_response: &'static str,
    pub lbl_model: &'static str,
    pub lbl_pdf_generating: &'static str,
    pub lbl_pdf_exported: &'static str,
    pub lbl_pdf_error: &'static str,
    pub lbl_pdf_pdf_label: &'static str,
    pub lbl_user_containers: &'static str,
    pub lbl_system_containers: &'static str,
    pub lbl_dont_close: &'static str,
    pub lbl_press_esc_close: &'static str,
    pub lbl_extraction_failed: &'static str,
    pub lbl_extraction_done: &'static str,
    pub lbl_node: &'static str,
    pub lbl_namespace: &'static str,
    pub lbl_context: &'static str,
    pub lbl_generated: &'static str,
    pub lbl_all_namespaces: &'static str,
    pub lbl_select_namespace: &'static str,
    pub lbl_export_empty_diag: &'static str,
    pub lbl_export_empty_usage: &'static str,
    pub lbl_filter_label_all: &'static str,
    pub lbl_filter_label_warn: &'static str,
    pub lbl_filter_label_err: &'static str,
    pub lbl_split: &'static str,
    pub lbl_total_label: &'static str,
    pub lbl_summary: &'static str,
    pub lbl_containers_to_watch: &'static str,
    pub lbl_no_issue: &'static str,
    pub lbl_recap: &'static str,
    pub lbl_node_diagnostic: &'static str,

    pub ai_send_to_ai_legend: &'static str,
    pub hint_select_copy: &'static str,

    pub progress_init: &'static str,
    pub progress_list_nodes: &'static str,
    pub progress_diag_collect: &'static str,
    pub progress_diag_ai: &'static str,
    pub progress_node_usage_fmt: &'static str,
    pub progress_node_ai_fmt: &'static str,
    pub progress_pdf: &'static str,
    pub progress_pdf_done: &'static str,
}

pub const FR: Strings = Strings {
    mode_live: "DIRECT",
    mode_selection: "SÉLECTION",
    mode_ns: "NS",
    mode_ai: "IA",
    mode_detail: "DÉTAIL",
    mode_nodes: "NOEUDS",
    mode_node_detail: "DÉTAIL-NOEUD",
    mode_node_usage: "USAGE-NOEUD",
    mode_diagnostic: "DIAGNOSTIC",
    mode_extract: "EXTRACTION",
    mode_command: "COMMANDE",
    mode_search: "RECHERCHE",
    search_hint_table: "ne garde que les lignes qui correspondent",
    search_hint_text: "surligne · Ctrl-N/Ctrl-P d'une occurrence à l'autre",
    mode_flux: "FLUX",
    mode_pods: "WORKLOADS",
    mode_rbac: "RBAC",
    mode_vuln: "VULN",
    mode_secrets: "SECRETS",
    mode_certs: "CERT-MANAGER",
    k_origin_cert: "chaîne cert-manager",
    k_cert_actions: "actions",
    k_goto_secret: "voir le secret",
    k_renew: "renouveler",
    k_acme_retry: "relancer ACME",
    mode_kyverno: "KYVERNO",
    k_ky_by_resource: "par ressource",
    k_ky_by_policy: "par policy",
    k_ky_filter: "filtre",
    mode_configmaps: "CONFIGMAPS",
    mode_services: "SERVICES",
    k_net_flat: "plat",
    k_net_byclass: "par class",

    k_quit: "quitter",
    k_select: "sélection",
    k_namespace: "namespace",
    k_nodes: "noeuds",
    k_command: "commande",
    k_search: "recherche",
    k_log_prev: "run précédent",
    k_log_container: "container",
    k_log_follow: "suivi",
    k_flux: "flux",
    k_diag: "diag",
    k_extract: "extraction→PDF",
    k_back: "retour",
    k_close: "fermer",
    k_zoom: "zoom détail",
    k_nav: "nav",
    k_view: "vue",
    k_scroll: "défil.",
    k_h_scroll: "défil. h.",
    k_page: "page",
    k_top_bot: "haut/bas",
    k_split: "split",
    k_ai: "IA",
    k_refresh: "rafraîchir",
    k_sort: "tri",
    k_relaunch: "relancer",
    k_pdf: "PDF",
    k_send_to_ai: "envoyer à l'IA",
    k_confirm: "valider",
    k_cancel: "annuler",
    k_lang: "lang",
    k_provider: "IA",
    k_node_usage: "usage",
    k_filter_all: "tous",
    k_filter_warn: "avert.",
    k_filter_err: "err.",
    k_freeze: "geler",
    k_unfreeze: "dégeler",
    k_reconcile: "reconcile",
    k_reconcile_src: "+source",
    k_sync_root: "sync racine",
    k_suspend: "suspend",
    k_tree: "arbre",
    k_inventory: "inventaire",
    k_fold: "plier/déplier",
    k_flux_logs: "logs",
    k_pods: "workloads",
    k_origin: "origine",
    k_scale_up: "+1",
    k_scale_down: "-1",
    k_scale_zero: "scale 0",
    k_rescale: "rescale",
    k_force: "recyclage",
    k_restart: "restart",
    k_actions: "actions",
    k_rbac_filter: "sévérité",
    k_scale: "scale",
    k_scale_set: "définir N…",
    k_toggle_wl: "workloads",
    k_ns_here: "filtrer ce ns",
    k_copy: "copier",
    k_reveal_b64: "base64",
    k_reveal_plain: "déchiffrer",
    k_yaml: "yaml",
    k_yaml_toggle: "brut/neat",
    lbl_yaml_neat: "neat",
    lbl_yaml_raw: "brut",
    k_delete: "supprimer",

    delete_title: "Suppression",
    delete_cancel_keys: "Entrée/Esc",
    delete_target: "Objet",
    delete_checking: "vérifications en cours…",
    delete_no_object: "suppression : aucun objet sélectionné",
    delete_no_finding: "Aucun garde-fou déclenché : objet autonome.",
    delete_check_failed: "Vérifications impossibles ({e}) : confirmation stricte exigée.",
    delete_arm_prompt: "Ctrl-D pour armer la suppression · Entrée/Esc annuler",
    delete_confirm_prompt: "Supprimer définitivement ? Ctrl-D = oui · Entrée/Esc = non",
    delete_strict_hint: "Ctrl-D pour passer outre l'avertissement · Entrée/Esc annuler",
    delete_strict_prompt: "Tapez le nom de l'objet puis Ctrl-D pour confirmer : {n}_",
    delete_strict_mismatch: "attendu : {name}",
    delete_running: "suppression en cours…",
    delete_ok: "✓ supprimé — l'API a accepté la demande",
    delete_failed: "✗ suppression refusée : {e}",
    del_flux_ks: "GitOps : appliqué par la Kustomization Flux {d} — sera recréé au prochain reconcile",
    del_flux_hr: "GitOps : appliqué par la HelmRelease Flux {d} — sera recréé au prochain reconcile",
    del_argo: "GitOps : appliqué par l'Application Argo CD {d} — sera recréé au prochain sync",
    del_helm: "Appartient à la release Helm {d} — la suppression désynchronise la release",
    del_gitops_root: "Point d'entrée GitOps ({d}) : supprime aussi tout ce qu'il déploie",
    del_namespace: "Namespace : supprime en cascade tout ce qu'il contient",
    del_crd: "CRD : supprime en cascade toutes les instances de ce type dans le cluster",
    del_owned: "Recréé aussitôt par son contrôleur ({d})",
    del_system_ns: "Namespace système ({d}) : touche le fonctionnement du cluster",
    del_node: "Noeud : à drainer (kubectl drain) avant suppression",
    del_persistent: "Stockage persistant : les données peuvent être perdues définitivement",
    del_finalizers: "Finalizers présents : la suppression peut rester bloquée en Terminating",

    k_edit: "éditer",
    edit_title: "Édition",
    edit_target: "Objet",
    edit_checking: "vérifications en cours…",
    edit_no_object: "édition : aucun objet sélectionné",
    edit_load_failed: "Chargement impossible : {e}",
    edit_open_prompt: "Entrée pour éditer quand même · Esc annuler",
    edit_editor_running: "édition en cours dans l'éditeur externe…",
    edit_editor_failed: "Éditeur : {e}",
    edit_no_change: "édition : document inchangé",
    edit_parse_error: "YAML invalide : {e}",
    edit_reedit_prompt: "Entrée ré-éditer · Esc abandonner",
    edit_changes: "{n} modification(s) :",
    edit_more_changes: "…et {n} de plus",
    edit_apply_prompt: "Entrée appliquer · e ré-éditer · Esc annuler",
    edit_applying: "application en cours…",
    edit_ok: "✓ appliqué — l'API a accepté la modification",
    edit_failed: "✗ modification refusée : {e}",
    edit_noop: "Seuls des champs gérés par l'API changent : appliquer ne modifiera rien",
    edit_server_owned: "Gérés par l'API, ignorés à l'application : {d}",
    edit_immutable: "Figés après création, l'API rejettera : {d}",
    edit_identity: "Identité modifiée ({d}) : ce n'est plus le même objet, l'API refusera",
    edit_header_object: "Édition de {d} via kdt.",
    edit_header_hint: "Enregistrez et quittez pour appliquer, quittez sans modifier pour annuler.",
    ed_flux_ks: "GitOps : appliqué par la Kustomization Flux {d} — écrasé au prochain reconcile, éditez le dépôt Git",
    ed_flux_hr: "GitOps : appliqué par la HelmRelease Flux {d} — écrasé au prochain reconcile, éditez les values dans Git",
    ed_argo: "GitOps : appliqué par l'Application Argo CD {d} — écrasé au prochain sync, éditez le dépôt Git",
    ed_helm: "Appartient à la release Helm {d} — modification perdue au prochain helm upgrade",
    ed_owned: "Spec tenue par son contrôleur ({d}) : perdue à la prochaine recréation, éditez plutôt le contrôleur",
    ed_terminating: "Objet en cours de suppression : la modification disparaîtra avec lui",
    ed_completed: "Pod terminé ({d}) : plus rien n'est actif, la modification n'aura aucun effet",
    ed_forbidden: "Droits insuffisants : l'API refuse le verbe update sur cet objet",
    ed_immutable_obj: "Marqué immutable: true — les données ne peuvent plus être modifiées",
    ed_running_pod: "Pod en cours d'exécution : seule l'image des conteneurs est modifiable à chaud",
    ed_partial_spec: "{d} : spec en grande partie figée après création, la plupart des champs seront rejetés",

    k_touch: "toucher",
    k_touch_object: "toucher l'objet",
    touch_no_object: "touch : aucun objet sélectionné",
    touch_running: "↻ touch {d}…",
    touch_ok: "✓ touché {d}",
    touch_failed: "✗ touch {d} : {e}",

    menu_pods_title: "Action sur le workload",
    menu_flux_title: "Réconciliation Flux",
    menu_certs_title: "Actions cert-manager",
    desc_renew: "Force le renouvellement du Certificate (condition Issuing=True, équivalent cmctl renew).",
    desc_acme_retry: "Supprime la CertificateRequest en cours pour relancer le cycle ACME (Order et Challenges supprimés en cascade). Refusé si un rate limit ACME est détecté.",
    menu_scale_title: "Scale du workload",
    menu_hint: "↑↓ choisir · Entrée valider · Esc annuler",
    menu_confirm_prompt: "Confirmer ? Entrée = oui · Esc = non",
    menu_input_prompt: "Répliques : {n}_ · Entrée valider · Esc annuler",
    desc_rescale: "Remet les répliques au nombre initial mémorisé (rolling update).",
    desc_recycle: "Scale à 0 puis remonte : recrée tous les pods d'un coup (coupure brève).",
    desc_restart: "kubectl rollout restart : redémarrage progressif, sans coupure.",
    desc_reconcile: "Réconcilie la ressource sélectionnée (annotation reconcile.fluxcd.io).",
    desc_reconcile_src: "Réconcilie d'abord la source (Git/Helm/OCI) puis la ressource.",
    desc_sync_root: "Réconcilie la GitRepository racine flux-system (resync complet).",
    desc_scale_up: "Ajoute une réplique au nombre actuel.",
    desc_scale_down: "Retire une réplique (minimum 0).",
    desc_scale_zero: "Scale à 0 : arrête tous les pods (le nombre initial reste mémorisé).",
    desc_scale_set: "Saisir le nombre exact de répliques voulu.",

    title_node_usage: "Usage du noeud",
    title_diagnostic: "Diagnostic cluster",
    title_namespace: "Namespace",
    title_ai_analysis: "Analyse IA",
    title_extraction: "Extraction",
    title_extraction_running: "Extraction en cours — ne pas fermer",
    title_extraction_finished: "Extraction — terminée",
    title_extraction_error: "Extraction — erreur",

    lbl_loading: "Chargement...",
    lbl_preparation: "Préparation...",
    lbl_ready: "prêt",
    lbl_running: "en cours…",
    lbl_finished: "terminé",
    lbl_error: "erreur",
    lbl_step: "Étape",
    lbl_steps: "étapes",
    lbl_duration: "durée",
    lbl_metrics_ok: "metrics-server : disponible",
    lbl_metrics_unavailable: "metrics-server : indisponible (use=—)",
    lbl_no_response: "(pas de réponse IA)",
    lbl_model: "Modèle",
    lbl_pdf_generating: "génération PDF (typst)...",
    lbl_pdf_exported: "exporté",
    lbl_pdf_error: "erreur export",
    lbl_pdf_pdf_label: "PDF",
    lbl_user_containers: "User containers",
    lbl_system_containers: "System containers",
    lbl_dont_close: "ne pas fermer",
    lbl_press_esc_close: "appuyer sur Esc pour fermer",
    lbl_extraction_failed: "Échec de l'extraction",
    lbl_extraction_done: "Extraction terminée",
    lbl_node: "Noeud",
    lbl_namespace: "Namespace",
    lbl_context: "Contexte",
    lbl_generated: "Généré",
    lbl_all_namespaces: "(tous les namespaces)",
    lbl_select_namespace: "Namespace · ↑↓ nav · Entrée valider · Esc annuler",
    lbl_export_empty_diag: "rien à exporter (diagnostic vide)",
    lbl_export_empty_usage: "rien à exporter (usage vide)",
    lbl_filter_label_all: "TOUS",
    lbl_filter_label_warn: "AVERT",
    lbl_filter_label_err: "ERR",
    lbl_split: "split",
    lbl_total_label: "total",
    lbl_summary: "Bilan",
    lbl_containers_to_watch: "Conteneurs à surveiller",
    lbl_no_issue: "Aucun conteneur avec un problème détecté.",
    lbl_recap: "Récap",
    lbl_node_diagnostic: "Diagnostic du noeud",

    ai_send_to_ai_legend: "envoie le rapport à l'IA",
    hint_select_copy: "Maj+glisser pour sélectionner / copier",

    progress_init: "Initialisation...",
    progress_list_nodes: "Liste des noeuds...",
    progress_diag_collect: "Diagnostic — collecte des indicateurs cluster...",
    progress_diag_ai: "Diagnostic — analyse IA...",
    progress_node_usage_fmt: "Noeud {i}/{n} — usage : {name}",
    progress_node_ai_fmt: "Noeud {i}/{n} — analyse IA : {name}",
    progress_pdf: "Génération du PDF...",
    progress_pdf_done: "PDF généré",
};

pub const EN: Strings = Strings {
    mode_live: "LIVE",
    mode_selection: "SELECT",
    mode_ns: "NS",
    mode_ai: "AI",
    mode_detail: "DETAIL",
    mode_nodes: "NODES",
    mode_node_detail: "NODE-DETAIL",
    mode_node_usage: "NODE-USAGE",
    mode_diagnostic: "DIAGNOSTIC",
    mode_extract: "EXTRACT",
    mode_command: "COMMAND",
    mode_search: "SEARCH",
    search_hint_table: "keeps only the rows that match",
    search_hint_text: "highlights · Ctrl-N/Ctrl-P to jump between matches",
    mode_flux: "FLUX",
    mode_pods: "WORKLOADS",
    mode_rbac: "RBAC",
    mode_vuln: "VULN",
    mode_secrets: "SECRETS",
    mode_certs: "CERT-MANAGER",
    k_origin_cert: "cert-manager chain",
    k_cert_actions: "actions",
    k_goto_secret: "show secret",
    k_renew: "renew",
    k_acme_retry: "retry ACME",
    mode_kyverno: "KYVERNO",
    k_ky_by_resource: "by resource",
    k_ky_by_policy: "by policy",
    k_ky_filter: "filter",
    mode_configmaps: "CONFIGMAPS",
    mode_services: "SERVICES",
    k_net_flat: "flat",
    k_net_byclass: "by class",

    k_quit: "quit",
    k_select: "select",
    k_namespace: "namespace",
    k_nodes: "nodes",
    k_command: "command",
    k_search: "search",
    k_log_prev: "previous run",
    k_log_container: "container",
    k_log_follow: "follow",
    k_flux: "flux",
    k_diag: "diag",
    k_extract: "extract→PDF",
    k_back: "back",
    k_close: "close",
    k_zoom: "zoom",
    k_nav: "nav",
    k_view: "view",
    k_scroll: "scroll",
    k_h_scroll: "h-scroll",
    k_page: "page",
    k_top_bot: "top/bot",
    k_split: "split",
    k_ai: "AI",
    k_refresh: "refresh",
    k_sort: "sort",
    k_relaunch: "rerun",
    k_pdf: "PDF",
    k_send_to_ai: "send to AI",
    k_confirm: "confirm",
    k_cancel: "cancel",
    k_lang: "lang",
    k_provider: "IA",
    k_node_usage: "usage",
    k_filter_all: "all",
    k_filter_warn: "warn",
    k_filter_err: "err",
    k_freeze: "freeze",
    k_unfreeze: "unfreeze",
    k_reconcile: "reconcile",
    k_reconcile_src: "+source",
    k_sync_root: "root sync",
    k_suspend: "suspend",
    k_tree: "tree",
    k_inventory: "inventory",
    k_fold: "fold/unfold",
    k_flux_logs: "logs",
    k_pods: "workloads",
    k_origin: "origin",
    k_scale_up: "+1",
    k_scale_down: "-1",
    k_scale_zero: "scale 0",
    k_rescale: "rescale",
    k_force: "recycle",
    k_restart: "restart",
    k_actions: "actions",
    k_rbac_filter: "severity",
    k_scale: "scale",
    k_scale_set: "set N…",
    k_toggle_wl: "workloads",
    k_ns_here: "filter this ns",
    k_copy: "copy",
    k_reveal_b64: "base64",
    k_reveal_plain: "decode",
    k_yaml: "yaml",
    k_yaml_toggle: "raw/neat",
    lbl_yaml_neat: "neat",
    lbl_yaml_raw: "raw",
    k_delete: "delete",

    delete_title: "Delete",
    delete_cancel_keys: "Enter/Esc",
    delete_target: "Object",
    delete_checking: "running checks…",
    delete_no_object: "delete: no object selected",
    delete_no_finding: "No guard-rail triggered: standalone object.",
    delete_check_failed: "Checks could not run ({e}): strict confirmation required.",
    delete_arm_prompt: "Ctrl-D to arm the deletion · Enter/Esc cancel",
    delete_confirm_prompt: "Delete for good? Ctrl-D = yes · Enter/Esc = no",
    delete_strict_hint: "Ctrl-D to override the warning · Enter/Esc cancel",
    delete_strict_prompt: "Type the object name then Ctrl-D to confirm: {n}_",
    delete_strict_mismatch: "expected: {name}",
    delete_running: "deleting…",
    delete_ok: "✓ deleted — the API accepted the request",
    delete_failed: "✗ deletion refused: {e}",
    del_flux_ks: "GitOps: applied by the Flux Kustomization {d} — will be recreated on next reconcile",
    del_flux_hr: "GitOps: applied by the Flux HelmRelease {d} — will be recreated on next reconcile",
    del_argo: "GitOps: applied by the Argo CD Application {d} — will be recreated on next sync",
    del_helm: "Owned by the Helm release {d} — deleting it desynchronises the release",
    del_gitops_root: "GitOps entry point ({d}): also removes everything it deploys",
    del_namespace: "Namespace: cascades to everything it contains",
    del_crd: "CRD: cascades to every instance of that type in the cluster",
    del_owned: "Immediately recreated by its controller ({d})",
    del_system_ns: "System namespace ({d}): affects how the cluster runs",
    del_node: "Node: drain it (kubectl drain) before deleting",
    del_persistent: "Persistent storage: data may be lost for good",
    del_finalizers: "Finalizers present: the deletion may hang in Terminating",

    k_edit: "edit",
    edit_title: "Edit",
    edit_target: "Object",
    edit_checking: "running checks…",
    edit_no_object: "edit: no object selected",
    edit_load_failed: "Could not load the object: {e}",
    edit_open_prompt: "Enter to edit anyway · Esc cancel",
    edit_editor_running: "editing in the external editor…",
    edit_editor_failed: "Editor: {e}",
    edit_no_change: "edit: document unchanged",
    edit_parse_error: "Invalid YAML: {e}",
    edit_reedit_prompt: "Enter re-edit · Esc discard",
    edit_changes: "{n} change(s):",
    edit_more_changes: "…and {n} more",
    edit_apply_prompt: "Enter apply · e re-edit · Esc cancel",
    edit_applying: "applying…",
    edit_ok: "✓ applied — the API accepted the change",
    edit_failed: "✗ change refused: {e}",
    edit_noop: "Only API-owned fields change: applying would leave the object as it is",
    edit_server_owned: "API-owned, ignored on apply: {d}",
    edit_immutable: "Frozen after creation, the API will reject: {d}",
    edit_identity: "Identity changed ({d}): this is no longer the same object, the API will refuse",
    edit_header_object: "Editing {d} through kdt.",
    edit_header_hint: "Save and quit to apply, quit without changes to cancel.",
    ed_flux_ks: "GitOps: applied by the Flux Kustomization {d} — overwritten on next reconcile, edit the Git repository",
    ed_flux_hr: "GitOps: applied by the Flux HelmRelease {d} — overwritten on next reconcile, edit the values in Git",
    ed_argo: "GitOps: applied by the Argo CD Application {d} — overwritten on next sync, edit the Git repository",
    ed_helm: "Owned by the Helm release {d} — the change is lost on the next helm upgrade",
    ed_owned: "Spec held by its controller ({d}): lost on the next recreation, edit the controller instead",
    ed_terminating: "Object is being deleted: the change goes away with it",
    ed_completed: "Finished pod ({d}): nothing is running any more, the change has no effect",
    ed_forbidden: "Not allowed: the API refuses the update verb on this object",
    ed_immutable_obj: "Marked immutable: true — its data can no longer be changed",
    ed_running_pod: "Running pod: only container images can be changed in place",
    ed_partial_spec: "{d}: the spec is mostly frozen after creation, most fields will be rejected",

    k_touch: "touch",
    k_touch_object: "touch object",
    touch_no_object: "touch: no object selected",
    touch_running: "↻ touching {d}…",
    touch_ok: "✓ touched {d}",
    touch_failed: "✗ touch {d}: {e}",

    menu_pods_title: "Workload action",
    menu_flux_title: "Flux reconcile",
    menu_certs_title: "cert-manager actions",
    desc_renew: "Forces the Certificate to be re-issued (Issuing=True condition, same as cmctl renew).",
    desc_acme_retry: "Deletes the in-flight CertificateRequest to restart the ACME cycle (Order and Challenges are garbage-collected with it). Refused when an ACME rate limit is detected.",
    menu_scale_title: "Scale workload",
    menu_hint: "↑↓ select · Enter confirm · Esc cancel",
    menu_confirm_prompt: "Confirm? Enter = yes · Esc = no",
    menu_input_prompt: "Replicas: {n}_ · Enter confirm · Esc cancel",
    desc_rescale: "Restore replicas to the memorised initial count (rolling update).",
    desc_recycle: "Scale to 0 then back up: recreate all pods at once (brief downtime).",
    desc_restart: "kubectl rollout restart: gradual restart, no downtime.",
    desc_reconcile: "Reconcile the selected resource (reconcile.fluxcd.io annotation).",
    desc_reconcile_src: "Reconcile the source first (Git/Helm/OCI) then the resource.",
    desc_sync_root: "Reconcile the root flux-system GitRepository (full resync).",
    desc_scale_up: "Add one replica to the current count.",
    desc_scale_down: "Remove one replica (minimum 0).",
    desc_scale_zero: "Scale to 0: stop all pods (the initial count stays memorised).",
    desc_scale_set: "Enter the exact replica count you want.",

    title_node_usage: "Node usage",
    title_diagnostic: "Cluster diagnostic",
    title_namespace: "Namespace",
    title_ai_analysis: "AI analysis",
    title_extraction: "Extraction",
    title_extraction_running: "Extraction running — do not close",
    title_extraction_finished: "Extraction — done",
    title_extraction_error: "Extraction — error",

    lbl_loading: "Loading...",
    lbl_preparation: "Preparing...",
    lbl_ready: "ready",
    lbl_running: "running…",
    lbl_finished: "done",
    lbl_error: "error",
    lbl_step: "Step",
    lbl_steps: "steps",
    lbl_duration: "duration",
    lbl_metrics_ok: "metrics-server: available",
    lbl_metrics_unavailable: "metrics-server: unavailable (use=—)",
    lbl_no_response: "(no AI response)",
    lbl_model: "Model",
    lbl_pdf_generating: "generating PDF (typst)...",
    lbl_pdf_exported: "exported",
    lbl_pdf_error: "export error",
    lbl_pdf_pdf_label: "PDF",
    lbl_user_containers: "User containers",
    lbl_system_containers: "System containers",
    lbl_dont_close: "do not close",
    lbl_press_esc_close: "press Esc to close",
    lbl_extraction_failed: "Extraction failed",
    lbl_extraction_done: "Extraction completed",
    lbl_node: "Node",
    lbl_namespace: "Namespace",
    lbl_context: "Context",
    lbl_generated: "Generated",
    lbl_all_namespaces: "(all namespaces)",
    lbl_select_namespace: "Namespace · ↑↓ nav · Enter confirm · Esc cancel",
    lbl_export_empty_diag: "nothing to export (empty diagnostic)",
    lbl_export_empty_usage: "nothing to export (empty usage)",
    lbl_filter_label_all: "ALL",
    lbl_filter_label_warn: "WARN",
    lbl_filter_label_err: "ERR",
    lbl_split: "split",
    lbl_total_label: "total",
    lbl_summary: "Summary",
    lbl_containers_to_watch: "Containers to watch",
    lbl_no_issue: "No container issue detected.",
    lbl_recap: "Recap",
    lbl_node_diagnostic: "Node diagnostic",

    ai_send_to_ai_legend: "send the report to AI",
    hint_select_copy: "Shift+drag to select / copy",

    progress_init: "Initialising...",
    progress_list_nodes: "Listing nodes...",
    progress_diag_collect: "Diagnostic — collecting cluster indicators...",
    progress_diag_ai: "Diagnostic — AI analysis...",
    progress_node_usage_fmt: "Node {i}/{n} — usage: {name}",
    progress_node_ai_fmt: "Node {i}/{n} — AI analysis: {name}",
    progress_pdf: "Generating PDF...",
    progress_pdf_done: "PDF generated",
};

// Return the string table for the active language.
pub fn t(lang: AiLanguage) -> &'static Strings {
    match lang {
        AiLanguage::Fr => &FR,
        AiLanguage::En => &EN,
    }
}
