//! Static FR/EN UI string tables, selected at runtime via [`t`].

use crate::ai::AiLanguage;

// `dead_code` is allowed because this is a translation table kept complete on purpose:
// several entries are reserved for UI strings not yet wired up and are intentionally unused.
#[allow(dead_code)]
pub struct Strings {
    pub mode_live: &'static str,
    pub mode_selection: &'static str,
    pub mode_ns: &'static str,
    pub mode_ai: &'static str,
    pub mode_detail: &'static str,
    pub mode_nodes: &'static str,
    pub mode_node_detail: &'static str,
    pub mode_node_usage: &'static str,
    pub mode_diagnostic: &'static str,
    pub mode_extract: &'static str,
    pub mode_command: &'static str,
    pub mode_flux: &'static str,
    pub mode_pods: &'static str,
    pub mode_rbac: &'static str,
    pub mode_vuln: &'static str,
    pub mode_secrets: &'static str,
    pub mode_configmaps: &'static str,

    pub k_quit: &'static str,
    pub k_select: &'static str,
    pub k_namespace: &'static str,
    pub k_nodes: &'static str,
    pub k_command: &'static str,
    pub k_flux: &'static str,
    pub k_diag: &'static str,
    pub k_extract: &'static str,
    pub k_back: &'static str,
    pub k_close: &'static str,
    pub k_zoom: &'static str,
    pub k_nav: &'static str,
    pub k_view: &'static str,
    pub k_scroll: &'static str,
    pub k_h_scroll: &'static str,
    pub k_page: &'static str,
    pub k_top_bot: &'static str,
    pub k_split: &'static str,
    pub k_ai: &'static str,
    pub k_refresh: &'static str,
    pub k_sort: &'static str,
    pub k_relaunch: &'static str,
    pub k_pdf: &'static str,
    pub k_send_to_ai: &'static str,
    pub k_confirm: &'static str,
    pub k_cancel: &'static str,
    pub k_lang: &'static str,
    pub k_provider: &'static str,
    pub k_node_usage: &'static str,
    pub k_filter_all: &'static str,
    pub k_filter_warn: &'static str,
    pub k_filter_err: &'static str,
    pub k_freeze: &'static str,
    pub k_unfreeze: &'static str,
    pub k_reconcile: &'static str,
    pub k_reconcile_src: &'static str,
    pub k_sync_root: &'static str,
    pub k_suspend: &'static str,
    pub k_tree: &'static str,
    pub k_inventory: &'static str,
    pub k_fold: &'static str,
    pub k_flux_logs: &'static str,
    pub k_pods: &'static str,
    pub k_origin: &'static str,
    pub k_scale_up: &'static str,
    pub k_scale_down: &'static str,
    pub k_scale_zero: &'static str,
    pub k_rescale: &'static str,
    pub k_force: &'static str,
    pub k_restart: &'static str,
    pub k_actions: &'static str,
    pub k_rbac_filter: &'static str,
    pub k_scale: &'static str,
    pub k_scale_set: &'static str,
    pub k_ns_here: &'static str,
    pub k_copy: &'static str,
    pub k_reveal_b64: &'static str,
    pub k_reveal_plain: &'static str,

    pub menu_pods_title: &'static str,
    pub menu_flux_title: &'static str,
    pub menu_scale_title: &'static str,
    pub menu_hint: &'static str,
    pub menu_confirm_prompt: &'static str,
    pub menu_input_prompt: &'static str,
    pub desc_rescale: &'static str,
    pub desc_recycle: &'static str,
    pub desc_restart: &'static str,
    pub desc_reconcile: &'static str,
    pub desc_reconcile_src: &'static str,
    pub desc_sync_root: &'static str,
    pub desc_scale_up: &'static str,
    pub desc_scale_down: &'static str,
    pub desc_scale_zero: &'static str,
    pub desc_scale_set: &'static str,

    pub title_node_usage: &'static str,
    pub title_diagnostic: &'static str,
    pub title_namespace: &'static str,
    pub title_ai_analysis: &'static str,
    pub title_extraction: &'static str,
    pub title_extraction_running: &'static str,
    pub title_extraction_finished: &'static str,
    pub title_extraction_error: &'static str,

    pub lbl_loading: &'static str,
    pub lbl_preparation: &'static str,
    pub lbl_ready: &'static str,
    pub lbl_running: &'static str,
    pub lbl_finished: &'static str,
    pub lbl_error: &'static str,
    pub lbl_step: &'static str,
    pub lbl_steps: &'static str,
    pub lbl_duration: &'static str,
    pub lbl_metrics_ok: &'static str,
    pub lbl_metrics_unavailable: &'static str,
    pub lbl_no_response: &'static str,
    pub lbl_model: &'static str,
    pub lbl_pdf_generating: &'static str,
    pub lbl_pdf_exported: &'static str,
    pub lbl_pdf_error: &'static str,
    pub lbl_pdf_pdf_label: &'static str,
    pub lbl_user_containers: &'static str,
    pub lbl_system_containers: &'static str,
    pub lbl_dont_close: &'static str,
    pub lbl_press_esc_close: &'static str,
    pub lbl_extraction_failed: &'static str,
    pub lbl_extraction_done: &'static str,
    pub lbl_node: &'static str,
    pub lbl_namespace: &'static str,
    pub lbl_context: &'static str,
    pub lbl_generated: &'static str,
    pub lbl_all_namespaces: &'static str,
    pub lbl_select_namespace: &'static str,
    pub lbl_export_empty_diag: &'static str,
    pub lbl_export_empty_usage: &'static str,
    pub lbl_filter_label_all: &'static str,
    pub lbl_filter_label_warn: &'static str,
    pub lbl_filter_label_err: &'static str,
    pub lbl_split: &'static str,
    pub lbl_total_label: &'static str,
    pub lbl_summary: &'static str,
    pub lbl_containers_to_watch: &'static str,
    pub lbl_no_issue: &'static str,
    pub lbl_recap: &'static str,
    pub lbl_node_diagnostic: &'static str,

    pub ai_send_to_ai_legend: &'static str,
    pub hint_select_copy: &'static str,

    pub progress_init: &'static str,
    pub progress_list_nodes: &'static str,
    pub progress_diag_collect: &'static str,
    pub progress_diag_ai: &'static str,
    pub progress_node_usage_fmt: &'static str,
    pub progress_node_ai_fmt: &'static str,
    pub progress_pdf: &'static str,
    pub progress_pdf_done: &'static str,
}

pub const FR: Strings = Strings {
    mode_live: "DIRECT",
    mode_selection: "SÉLECTION",
    mode_ns: "NS",
    mode_ai: "IA",
    mode_detail: "DÉTAIL",
    mode_nodes: "NOEUDS",
    mode_node_detail: "DÉTAIL-NOEUD",
    mode_node_usage: "USAGE-NOEUD",
    mode_diagnostic: "DIAGNOSTIC",
    mode_extract: "EXTRACTION",
    mode_command: "COMMANDE",
    mode_flux: "FLUX",
    mode_pods: "WORKLOADS",
    mode_rbac: "RBAC",
    mode_vuln: "VULN",
    mode_secrets: "SECRETS",
    mode_configmaps: "CONFIGMAPS",

    k_quit: "quitter",
    k_select: "sélection",
    k_namespace: "namespace",
    k_nodes: "noeuds",
    k_command: "commande",
    k_flux: "flux",
    k_diag: "diag",
    k_extract: "extraction→PDF",
    k_back: "retour",
    k_close: "fermer",
    k_zoom: "zoom détail",
    k_nav: "nav",
    k_view: "vue",
    k_scroll: "défil.",
    k_h_scroll: "défil. h.",
    k_page: "page",
    k_top_bot: "haut/bas",
    k_split: "split",
    k_ai: "IA",
    k_refresh: "rafraîchir",
    k_sort: "tri",
    k_relaunch: "relancer",
    k_pdf: "PDF",
    k_send_to_ai: "envoyer à l'IA",
    k_confirm: "valider",
    k_cancel: "annuler",
    k_lang: "lang",
    k_provider: "IA",
    k_node_usage: "usage",
    k_filter_all: "tous",
    k_filter_warn: "avert.",
    k_filter_err: "err.",
    k_freeze: "geler",
    k_unfreeze: "dégeler",
    k_reconcile: "reconcile",
    k_reconcile_src: "+source",
    k_sync_root: "sync racine",
    k_suspend: "suspend",
    k_tree: "arbre",
    k_inventory: "inventaire",
    k_fold: "plier/déplier",
    k_flux_logs: "logs",
    k_pods: "workloads",
    k_origin: "origine",
    k_scale_up: "+1",
    k_scale_down: "-1",
    k_scale_zero: "scale 0",
    k_rescale: "rescale",
    k_force: "recyclage",
    k_restart: "restart",
    k_actions: "actions",
    k_rbac_filter: "sévérité",
    k_scale: "scale",
    k_scale_set: "définir N…",
    k_ns_here: "filtrer ce ns",
    k_copy: "copier",
    k_reveal_b64: "base64",
    k_reveal_plain: "déchiffrer",

    menu_pods_title: "Action sur le workload",
    menu_flux_title: "Réconciliation Flux",
    menu_scale_title: "Scale du workload",
    menu_hint: "↑↓ choisir · Entrée valider · Esc annuler",
    menu_confirm_prompt: "Confirmer ? Entrée = oui · Esc = non",
    menu_input_prompt: "Répliques : {n}_ · Entrée valider · Esc annuler",
    desc_rescale: "Remet les répliques au nombre initial mémorisé (rolling update).",
    desc_recycle: "Scale à 0 puis remonte : recrée tous les pods d'un coup (coupure brève).",
    desc_restart: "kubectl rollout restart : redémarrage progressif, sans coupure.",
    desc_reconcile: "Réconcilie la ressource sélectionnée (annotation reconcile.fluxcd.io).",
    desc_reconcile_src: "Réconcilie d'abord la source (Git/Helm/OCI) puis la ressource.",
    desc_sync_root: "Réconcilie la GitRepository racine flux-system (resync complet).",
    desc_scale_up: "Ajoute une réplique au nombre actuel.",
    desc_scale_down: "Retire une réplique (minimum 0).",
    desc_scale_zero: "Scale à 0 : arrête tous les pods (le nombre initial reste mémorisé).",
    desc_scale_set: "Saisir le nombre exact de répliques voulu.",

    title_node_usage: "Usage du noeud",
    title_diagnostic: "Diagnostic cluster",
    title_namespace: "Namespace",
    title_ai_analysis: "Analyse IA",
    title_extraction: "Extraction",
    title_extraction_running: "Extraction en cours — ne pas fermer",
    title_extraction_finished: "Extraction — terminée",
    title_extraction_error: "Extraction — erreur",

    lbl_loading: "Chargement...",
    lbl_preparation: "Préparation...",
    lbl_ready: "prêt",
    lbl_running: "en cours…",
    lbl_finished: "terminé",
    lbl_error: "erreur",
    lbl_step: "Étape",
    lbl_steps: "étapes",
    lbl_duration: "durée",
    lbl_metrics_ok: "metrics-server : disponible",
    lbl_metrics_unavailable: "metrics-server : indisponible (use=—)",
    lbl_no_response: "(pas de réponse IA)",
    lbl_model: "Modèle",
    lbl_pdf_generating: "génération PDF (typst)...",
    lbl_pdf_exported: "exporté",
    lbl_pdf_error: "erreur export",
    lbl_pdf_pdf_label: "PDF",
    lbl_user_containers: "User containers",
    lbl_system_containers: "System containers",
    lbl_dont_close: "ne pas fermer",
    lbl_press_esc_close: "appuyer sur Esc pour fermer",
    lbl_extraction_failed: "Échec de l'extraction",
    lbl_extraction_done: "Extraction terminée",
    lbl_node: "Noeud",
    lbl_namespace: "Namespace",
    lbl_context: "Contexte",
    lbl_generated: "Généré",
    lbl_all_namespaces: "(tous les namespaces)",
    lbl_select_namespace: "Namespace · ↑↓ nav · Entrée valider · Esc annuler",
    lbl_export_empty_diag: "rien à exporter (diagnostic vide)",
    lbl_export_empty_usage: "rien à exporter (usage vide)",
    lbl_filter_label_all: "TOUS",
    lbl_filter_label_warn: "AVERT",
    lbl_filter_label_err: "ERR",
    lbl_split: "split",
    lbl_total_label: "total",
    lbl_summary: "Bilan",
    lbl_containers_to_watch: "Conteneurs à surveiller",
    lbl_no_issue: "Aucun conteneur avec un problème détecté.",
    lbl_recap: "Récap",
    lbl_node_diagnostic: "Diagnostic du noeud",

    ai_send_to_ai_legend: "envoie le rapport à l'IA",
    hint_select_copy: "Maj+glisser pour sélectionner / copier",

    progress_init: "Initialisation...",
    progress_list_nodes: "Liste des noeuds...",
    progress_diag_collect: "Diagnostic — collecte des indicateurs cluster...",
    progress_diag_ai: "Diagnostic — analyse IA...",
    progress_node_usage_fmt: "Noeud {i}/{n} — usage : {name}",
    progress_node_ai_fmt: "Noeud {i}/{n} — analyse IA : {name}",
    progress_pdf: "Génération du PDF...",
    progress_pdf_done: "PDF généré",
};

pub const EN: Strings = Strings {
    mode_live: "LIVE",
    mode_selection: "SELECT",
    mode_ns: "NS",
    mode_ai: "AI",
    mode_detail: "DETAIL",
    mode_nodes: "NODES",
    mode_node_detail: "NODE-DETAIL",
    mode_node_usage: "NODE-USAGE",
    mode_diagnostic: "DIAGNOSTIC",
    mode_extract: "EXTRACT",
    mode_command: "COMMAND",
    mode_flux: "FLUX",
    mode_pods: "WORKLOADS",
    mode_rbac: "RBAC",
    mode_vuln: "VULN",
    mode_secrets: "SECRETS",
    mode_configmaps: "CONFIGMAPS",

    k_quit: "quit",
    k_select: "select",
    k_namespace: "namespace",
    k_nodes: "nodes",
    k_command: "command",
    k_flux: "flux",
    k_diag: "diag",
    k_extract: "extract→PDF",
    k_back: "back",
    k_close: "close",
    k_zoom: "zoom",
    k_nav: "nav",
    k_view: "view",
    k_scroll: "scroll",
    k_h_scroll: "h-scroll",
    k_page: "page",
    k_top_bot: "top/bot",
    k_split: "split",
    k_ai: "AI",
    k_refresh: "refresh",
    k_sort: "sort",
    k_relaunch: "rerun",
    k_pdf: "PDF",
    k_send_to_ai: "send to AI",
    k_confirm: "confirm",
    k_cancel: "cancel",
    k_lang: "lang",
    k_provider: "IA",
    k_node_usage: "usage",
    k_filter_all: "all",
    k_filter_warn: "warn",
    k_filter_err: "err",
    k_freeze: "freeze",
    k_unfreeze: "unfreeze",
    k_reconcile: "reconcile",
    k_reconcile_src: "+source",
    k_sync_root: "root sync",
    k_suspend: "suspend",
    k_tree: "tree",
    k_inventory: "inventory",
    k_fold: "fold/unfold",
    k_flux_logs: "logs",
    k_pods: "workloads",
    k_origin: "origin",
    k_scale_up: "+1",
    k_scale_down: "-1",
    k_scale_zero: "scale 0",
    k_rescale: "rescale",
    k_force: "recycle",
    k_restart: "restart",
    k_actions: "actions",
    k_rbac_filter: "severity",
    k_scale: "scale",
    k_scale_set: "set N…",
    k_ns_here: "filter this ns",
    k_copy: "copy",
    k_reveal_b64: "base64",
    k_reveal_plain: "decode",

    menu_pods_title: "Workload action",
    menu_flux_title: "Flux reconcile",
    menu_scale_title: "Scale workload",
    menu_hint: "↑↓ select · Enter confirm · Esc cancel",
    menu_confirm_prompt: "Confirm? Enter = yes · Esc = no",
    menu_input_prompt: "Replicas: {n}_ · Enter confirm · Esc cancel",
    desc_rescale: "Restore replicas to the memorised initial count (rolling update).",
    desc_recycle: "Scale to 0 then back up: recreate all pods at once (brief downtime).",
    desc_restart: "kubectl rollout restart: gradual restart, no downtime.",
    desc_reconcile: "Reconcile the selected resource (reconcile.fluxcd.io annotation).",
    desc_reconcile_src: "Reconcile the source first (Git/Helm/OCI) then the resource.",
    desc_sync_root: "Reconcile the root flux-system GitRepository (full resync).",
    desc_scale_up: "Add one replica to the current count.",
    desc_scale_down: "Remove one replica (minimum 0).",
    desc_scale_zero: "Scale to 0: stop all pods (the initial count stays memorised).",
    desc_scale_set: "Enter the exact replica count you want.",

    title_node_usage: "Node usage",
    title_diagnostic: "Cluster diagnostic",
    title_namespace: "Namespace",
    title_ai_analysis: "AI analysis",
    title_extraction: "Extraction",
    title_extraction_running: "Extraction running — do not close",
    title_extraction_finished: "Extraction — done",
    title_extraction_error: "Extraction — error",

    lbl_loading: "Loading...",
    lbl_preparation: "Preparing...",
    lbl_ready: "ready",
    lbl_running: "running…",
    lbl_finished: "done",
    lbl_error: "error",
    lbl_step: "Step",
    lbl_steps: "steps",
    lbl_duration: "duration",
    lbl_metrics_ok: "metrics-server: available",
    lbl_metrics_unavailable: "metrics-server: unavailable (use=—)",
    lbl_no_response: "(no AI response)",
    lbl_model: "Model",
    lbl_pdf_generating: "generating PDF (typst)...",
    lbl_pdf_exported: "exported",
    lbl_pdf_error: "export error",
    lbl_pdf_pdf_label: "PDF",
    lbl_user_containers: "User containers",
    lbl_system_containers: "System containers",
    lbl_dont_close: "do not close",
    lbl_press_esc_close: "press Esc to close",
    lbl_extraction_failed: "Extraction failed",
    lbl_extraction_done: "Extraction completed",
    lbl_node: "Node",
    lbl_namespace: "Namespace",
    lbl_context: "Context",
    lbl_generated: "Generated",
    lbl_all_namespaces: "(all namespaces)",
    lbl_select_namespace: "Namespace · ↑↓ nav · Enter confirm · Esc cancel",
    lbl_export_empty_diag: "nothing to export (empty diagnostic)",
    lbl_export_empty_usage: "nothing to export (empty usage)",
    lbl_filter_label_all: "ALL",
    lbl_filter_label_warn: "WARN",
    lbl_filter_label_err: "ERR",
    lbl_split: "split",
    lbl_total_label: "total",
    lbl_summary: "Summary",
    lbl_containers_to_watch: "Containers to watch",
    lbl_no_issue: "No container issue detected.",
    lbl_recap: "Recap",
    lbl_node_diagnostic: "Node diagnostic",

    ai_send_to_ai_legend: "send the report to AI",
    hint_select_copy: "Shift+drag to select / copy",

    progress_init: "Initialising...",
    progress_list_nodes: "Listing nodes...",
    progress_diag_collect: "Diagnostic — collecting cluster indicators...",
    progress_diag_ai: "Diagnostic — AI analysis...",
    progress_node_usage_fmt: "Node {i}/{n} — usage: {name}",
    progress_node_ai_fmt: "Node {i}/{n} — AI analysis: {name}",
    progress_pdf: "Generating PDF...",
    progress_pdf_done: "PDF generated",
};

// Return the string table for the active language.
pub fn t(lang: AiLanguage) -> &'static Strings {
    match lang {
        AiLanguage::Fr => &FR,
        AiLanguage::En => &EN,
    }
}
