# .github/workflows/release.yml
name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-macos:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin,x86_64-apple-darwin

      - name: Get app name
        run: echo "APP_NAME=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].name')" >> $GITHUB_ENV

      - name: Install dependencies
        run: brew install pkg-config

      - run: cargo build --release --target aarch64-apple-darwin

      - run: cargo build --release --target x86_64-apple-darwin

      - run: |
          lipo -create -output $APP_NAME \
            target/aarch64-apple-darwin/release/$APP_NAME \
            target/x86_64-apple-darwin/release/$APP_NAME

      - run: tar czf $APP_NAME-macos-universal.tar.gz $APP_NAME

      - uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.APP_NAME }}-macos-universal.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-homebrew:
    runs-on: ubuntu-latest
    needs: build-macos
    steps:
      - uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: kdt
          homebrew-tap: agardenat/homebrew-kdt
          download-url: https://github.com/agardenat/kdt/releases/download/${{ github.ref_name }}/kdt-macos-universal.tar.gz
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}